Wed Jan 18 06:40:38 2023
Windows-10-10.0.19044
Ren'Py 8.0.3.22090809
 

Bootstrap to the start of init.init took 0.19s
Early init took 0.01s
Loader init took 0.12s
Loading error handling took 0.09s
Loading script took 0.72s
Loading save slot metadata. took 0.11s
Loading persistent took 0.00s
Faled to initialize steam: FileNotFoundError("Could not find module 'C:\\renpy\\renpy-8.0.3-sdk\\lib\\py3-windows-x86_64\\steam_api64.dll' (or one of its dependencies). Try using the full path with constructor syntax.")
Running init code took 0.24s
Loading analysis data took 0.05s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Dump and make backups. took 0.15s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.07s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 0.01s
Cleaning stores took 0.00s
Init translation took 0.12s
Build styles took 0.01s
Load screen analysis took 0.07s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.18s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Performance test:
Interface start took 0.31s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1600, 900)
swap interval: 1 frames
Fullscreen mode.
Vendor: "b'ATI Technologies Inc.'"
Renderer: b'AMD Radeon(TM) R4 Graphics'
Version: b'4.6.13596 Compatibility Profile Context 20.10.44 27.20.11044.7'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1600, 900) drawable=(1600, 900)
Maximum texture size: 4096x4096

Full traceback:
  File "game/script.rpy", line 33, in script call
    call preparation_for_festaval from _call_preparation_for_festaval
  File "game/script.rpy", line 248, in script
    футаро "На сегодня все, потом обсудим еще раз."
  File "C:\renpy\renpy-8.0.3-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\renpy\renpy-8.0.3-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\renpy\renpy-8.0.3-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\renpy\renpy-8.0.3-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "C:\renpy\renpy-8.0.3-sdk\renpy\character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\renpy\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\renpy\renpy-8.0.3-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\renpy\renpy-8.0.3-sdk\renpy\display\core.py", line 3846, in interact_core
    renpy.audio.audio.interact()
  File "C:\renpy\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1213, in interact
    periodic()
  File "C:\renpy\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1166, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "C:\renpy\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1144, in periodic_thread_main
    periodic_pass()
  File "C:\renpy\renpy-8.0.3-sdk\renpy\audio\audio.py", line 1086, in periodic_pass
    c.periodic()
  File "C:\renpy\renpy-8.0.3-sdk\renpy\audio\audio.py", line 438, in periodic
    force_stop = self.context.force_stop or (renpy.game.preferences.mute.get(self.mixer, False) and self.stop_on_mute)
  File "C:\renpy\renpy-8.0.3-sdk\renpy\audio\audio.py", line 316, in get_context
    mcd = renpy.game.context().music
  File "C:\renpy\renpy-8.0.3-sdk\renpy\game.py", line 248, in context
    return contexts[index]
IndexError: list index out of range

While running game code:
  File "game/script.rpy", line 33, in script call
    call preparation_for_festaval from _call_preparation_for_festaval
  File "game/script.rpy", line 248, in script
    футаро "На сегодня все, потом обсудим еще раз."
IndexError: list index out of range
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.01s
Load screen analysis took 0.06s
Analyze screens took 0.00s
Prepare screens took 0.00s
Running _start took 0.01s
